# shared/unit.mk — included by every unit-level Makefile.

PROJECT_ROOT := $(abspath ..)
UNIT         := $(notdir $(CURDIR))
COMPILED_DIR := $(PROJECT_ROOT)/target/compiled

# Auto-discover lessons that have a Makefile, in sorted order.
LESSONS := $(patsubst %/Makefile,%,$(sort $(wildcard lesson*/Makefile)))

# Optional unit-level bookend components.
#
# binder_cover/ is a prefab-PDF component like sample_test/, with one
# difference: its main.pdf is generated by shared/cover.py rather than dropped
# in by hand. A unit opts in by having the directory at all. Its two identical
# pages are the front and back of the student's binder, so it leads the packet,
# ahead of the unit overview sheet.
HAS_BINDER_COVER := $(wildcard binder_cover)
HAS_UNIT_COVER  := $(wildcard unit_cover/main.tex)
HAS_SAMPLE_TEST     := $(wildcard sample_test/main.pdf)
HAS_SAMPLE_TEST_KEY := $(wildcard sample_test_key/main.pdf)

BINDER_COVER_SRC    := $(if $(HAS_BINDER_COVER),binder_cover/main.pdf)
BINDER_COVER_PDF    := $(if $(HAS_BINDER_COVER),$(COMPILED_DIR)/$(UNIT)/binder_cover.pdf)
UNIT_COVER_PDF      := $(if $(HAS_UNIT_COVER),$(COMPILED_DIR)/$(UNIT)/unit_cover.pdf)
SAMPLE_TEST_PDF     := $(if $(HAS_SAMPLE_TEST),$(COMPILED_DIR)/$(UNIT)/sample_test.pdf)
SAMPLE_TEST_KEY_PDF := $(if $(HAS_SAMPLE_TEST_KEY),$(COMPILED_DIR)/$(UNIT)/sample_test_key.pdf)

# What the cover is actually derived from, so it rebuilds when its content
# changes and stays put otherwise. With a hand-tuned spec that is the spec plus
# the lesson plan the unit title is read from; without one, auto-discovery
# reads the lesson components instead, so those become the inputs.
PYTHON       ?= python3
COVER_SCRIPT := $(PROJECT_ROOT)/shared/cover.py
COVER_SPEC   := $(wildcard binder_cover/spec.py)
COVER_TITLE  := $(firstword $(sort $(wildcard lesson*/main.tex)))
COVER_SCAN   := $(if $(COVER_SPEC),,$(wildcard lesson*/notes/main.tex \
                  lesson*/activity/main.tex lesson*/homework/main.tex))
COVER_DEPS   := $(COVER_SCRIPT) $(COVER_SPEC) $(COVER_TITLE) $(COVER_SCAN)

# A unit aggregates only the two packets that concatenate meaningfully. The
# other three lesson products (plan, 3-up slides PDF, slides PPTX) stay per-lesson —
# they are teacher artifacts, not something to hand out as one bound document.
.PHONY: all student key clean $(LESSONS) \
        binder_cover _binder_cover _unit_cover _sample_test _sample_test_key

all: _binder_cover $(LESSONS)

$(LESSONS):
	$(MAKE) -C $@

# ── Optional bookend rules ────────────────────────────────────────────────────

# The generated prefab. Declared .PHONY above so the binder_cover/ directory
# never shadows the convenience target of the same name.
ifdef HAS_BINDER_COVER
binder_cover: $(BINDER_COVER_SRC)

$(BINDER_COVER_SRC): $(COVER_DEPS)
	$(PYTHON) $(COVER_SCRIPT) $(CURDIR)
endif

_binder_cover: $(BINDER_COVER_SRC)
ifdef HAS_BINDER_COVER
	@mkdir -p $(COMPILED_DIR)/$(UNIT)
	@cp $(BINDER_COVER_SRC) $(BINDER_COVER_PDF)
	@echo "✓  Binder cover      → target/compiled/$(UNIT)/binder_cover.pdf"
endif

_unit_cover:
ifdef HAS_UNIT_COVER
	@mkdir -p $(COMPILED_DIR)/$(UNIT)
	cd unit_cover && TEXINPUTS="$(PROJECT_ROOT)/shared//:" \
	    latexmk -xelatex -interaction=nonstopmode -halt-on-error -file-line-error \
	    -outdir="$(PROJECT_ROOT)/target/$(UNIT)/unit_cover" main.tex
	cp $(PROJECT_ROOT)/target/$(UNIT)/unit_cover/main.pdf $(UNIT_COVER_PDF)
	@echo "✓  Unit cover        → target/compiled/$(UNIT)/unit_cover.pdf"
endif

_sample_test:
ifdef HAS_SAMPLE_TEST
	@mkdir -p $(COMPILED_DIR)/$(UNIT)
	cp sample_test/main.pdf $(SAMPLE_TEST_PDF)
	@echo "✓  Sample test       → target/compiled/$(UNIT)/sample_test.pdf"
endif

_sample_test_key:
ifdef HAS_SAMPLE_TEST_KEY
	@mkdir -p $(COMPILED_DIR)/$(UNIT)
	cp sample_test_key/main.pdf $(SAMPLE_TEST_KEY_PDF)
	@echo "✓  Sample test key   → target/compiled/$(UNIT)/sample_test_key.pdf"
endif

# ── student / key targets ─────────────────────────────────────────────────────
#
# The unit key packet mirrors the unit student packet piece for piece: the same
# unit cover, each lesson's key packet in place of its student packet (those are
# equal-length and equal-paginated by lesson.mk), and the sample test key in
# place of the sample test. Only that last pair can differ in length, and it
# sits at the end, so page N of the unit key is page N of the unit student
# packet up to the sample test.

student: _binder_cover _unit_cover $(LESSONS) _sample_test
	@for l in $(LESSONS); do $(MAKE) -C $$l student || exit 1; done
	@mkdir -p $(COMPILED_DIR)/$(UNIT) $(COMPILED_DIR)
	@lesson_pdfs=$$(ls $(COMPILED_DIR)/$(UNIT)/lesson*_student.pdf 2>/dev/null | sort); \
	all_pdfs="$(BINDER_COVER_PDF) $(UNIT_COVER_PDF) $$lesson_pdfs $(SAMPLE_TEST_PDF)"; \
	all_pdfs=$$(echo $$all_pdfs | tr ' ' '\n' | grep -v '^$$'); \
	if [ -n "$$all_pdfs" ]; then \
	  pdfunite $$all_pdfs $(COMPILED_DIR)/$(UNIT)_student.pdf; \
	  echo "✓  Unit student packet → target/compiled/$(UNIT)_student.pdf"; \
	else \
	  echo "  (no student PDFs found for $(UNIT))"; \
	fi

key: _binder_cover _unit_cover $(LESSONS) _sample_test _sample_test_key
	@for l in $(LESSONS); do $(MAKE) -C $$l key || exit 1; done
	@mkdir -p $(COMPILED_DIR)/$(UNIT) $(COMPILED_DIR)
	@lesson_pdfs=$$(ls $(COMPILED_DIR)/$(UNIT)/lesson*_key.pdf 2>/dev/null | sort); \
	all_pdfs="$(BINDER_COVER_PDF) $(UNIT_COVER_PDF) $$lesson_pdfs $(or $(SAMPLE_TEST_KEY_PDF),$(SAMPLE_TEST_PDF))"; \
	all_pdfs=$$(echo $$all_pdfs | tr ' ' '\n' | grep -v '^$$'); \
	if [ -n "$$all_pdfs" ]; then \
	  pdfunite $$all_pdfs $(COMPILED_DIR)/$(UNIT)_key.pdf; \
	  echo "✓  Unit key packet     → target/compiled/$(UNIT)_key.pdf"; \
	else \
	  echo "  (no key PDFs found for $(UNIT))"; \
	fi

clean:
	@for l in $(LESSONS); do $(MAKE) -C $$l clean; done
	rm -rf $(PROJECT_ROOT)/target/$(UNIT)/unit_cover
	rm -f $(BINDER_COVER_PDF) $(UNIT_COVER_PDF) $(SAMPLE_TEST_PDF) $(SAMPLE_TEST_KEY_PDF)
	rm -f $(COMPILED_DIR)/$(UNIT)_student.pdf $(COMPILED_DIR)/$(UNIT)_key.pdf \
	      $(COMPILED_DIR)/$(UNIT)_full.pdf
